travis:
  secure:
    BINSTAR_TOKEN: Ff3AXE8Y+N9BaceHOc1LxNZgT+4ZJ1Hs6qFy0uQH7NydqlKStPvJTR0S8Jz1BRsCjXHR4L0UlXdBcxUtiG0r6Gxy3z8Xib073mMUuIzKAvc3x54Y4e1kgT5kgP/mA/04rW3nHfbCQctm2CPlZne1vmmiyhkJ0SUADKFax8t79dW4vWS210dSmzNb8ik8gVpI1JnA0qQkI+1Jp/D4qPLWyDmuJD45vGKDtPkp9TFBYLk2M31p3QMe0jRdYvNNrVotv3bHUtmI40MbQlHdx/eOdpAPaphuTBp7KepU60AuvhUIG4P7yTlfU+xkZGnYCzqsusm/+H69TXa16iZzKRVcs41v0l7/+m4lEVoIzASJYx3KNQeQY456hdordpZLpE4r+Xao8IvCa1jCGDK1MUWc9HtTiouL5oIElpsLuMMLrIRMy4XLL2x0lai1d/HSzFcMWEmSm3eG+jpSskvgpym29xrw1w3yfT5hU4WU+Pg2zk0LWECl42sNL+a7lRw3yrbtZjSKAWjVtLcbyjUsJ2V7hPaPCf+Bhi62DAozeH7Y0rg8/eorGJItQLY8/fbGOcZAPi5Dta4bvwM4az1Die5QlR3rHSazvLmCNkQxREZf4r774LRXNunu5Y8KlNJxfz85pzvc4SNtg61mH5+fs5nYIZMeWVDx3gOPi70evACngOM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
